" line numbers
set nu

" syntax highlighting
syntax on

" indentation
set autoindent

" tab expansion to 2 spaces, as is good and proper
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=2

" update wrapping
set linebreak

call plug#begin('~/.vim/plugged')
Plug 'mileszs/ack.vim'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rails'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'dracula/vim', {'as': 'dracula'}
Plug 't9md/vim-ruby-xmpfilter'
Plug 'editorconfig/editorconfig-vim'
call plug#end()

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
	" Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0

  " bind K to grep word under cursor
  nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

  " update ignore
  set wildignore+=*/coverage/*,*.swp,*/node_modules/*
  let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
endif

" use Dracula theme
color dracula

map \ :NERDTreeToggle<CR>
map \| :NERDTreeFind<CR>
let NERDTreeShowHidden = 0
let NERDTreeRespectWhildIgnore = 1
let NERDTreeIgnore = ['\.pyc$', '\.swp$']

" Set Escape key timeout
" https://www.johnhawthorn.com/2012/09/vi-escape-delays/
set timeoutlen=10 ttimeoutlen=10

" Always display status line
set laststatus=2

" set space to leader
let mapleader = "\<Space>"

let g:xmpfilter_cmd = "seeing_is_believing"

 " autocmd FileType ruby nmap <buffer> <Leader>m <Plug>(seeing_is_believing-mark)
 " autocmd FileType ruby xmap <buffer> <Leader>m <Plug>(seeing_is_believing-mark)
 " autocmd FileType ruby imap <buffer> <Leader>m <Plug>(seeing_is_believing-mark)
 " 
 " autocmd FileType ruby nmap <buffer> <Leader>c <Plug>(seeing_is_believing-clean)
 " autocmd FileType ruby xmap <buffer> <Leader>c <Plug>(seeing_is_believing-clean)
 " autocmd FileType ruby imap <buffer> <Leader>c <Plug>(seeing_is_believing-clean)
 " 
 " " xmpfilter compatible
 " autocmd FileType ruby nmap <buffer> <Leader>r <Plug>(seeing_is_believing-run_-x)
 " autocmd FileType ruby xmap <buffer> <Leader>r <Plug>(seeing_is_believing-run_-x)
 " autocmd FileType ruby imap <buffer> <Leader>r <Plug>(seeing_is_believing-run_-x)

" " auto insert mark at appropriate spot.
" autocmd FileType ruby nmap <buffer> <Leader>r <Plug>(seeing_is_believing-run)
" autocmd FileType ruby xmap <buffer> <Leader>r <Plug>(seeing_is_believing-run)
" autocmd FileType ruby imap <buffer> <Leader>r <Plug>(seeing_is_believing-run)
