" line numbers
set nu

" syntax highlighting
syntax on

" indentation
set autoindent

" tab expansion to 2 spaces, as is good and proper
set expandtab
set ts=2

call plug#begin('~/.vim/plugged')
Plug 'mileszs/ack.vim'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rails'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'dracula/vim', {'as': 'dracula'}
call plug#end()

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
	" Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0

  " bind K to grep word under cursor
  nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
endif

" use Dracula theme
color dracula
